### ISSUE TITLE
2. Data persistence

### ISSUE THREAD

**Issue by oliverwebr** [dci-ber-fbw21/students-app-live#3]
Please write students data into a file in `<project_folder>/data/students.json`

**Comment by rene-mdd** [comment]
@oliverwebr I already have the file displaying the info in the console with readFileSync and JSON.parse. but I don't know where to put the fs.writeFile function.

**Comment by oliverwebr** [comment]
@rene-mdd 

Every time some one requests information we want to read the file, every time someone adds or removes data we want to write to our file.

So schematically for post you want to do this:

```js
app.post("/api/students", (req, res) => {
   const students = readFile()
   students.push(req.body)
   writeFile(students)
   res.send(students)
})
```
